### ISSUE TITLE
GitHub Link?

### ISSUE THREAD

**Issue by lynnwallenstein** [absinthe-graphql/website#10]
Do you want a header icon or banner or something linking to the GitHub repo?

**Comment by bruce** [comment]
Since this backs multiple projects I think having a github link (even just to the org) might not be really helpful.

Instead, we should push people to the "Projects" page. We could call that "Code" instead, I guess?

In addition to GitHub, perhaps we can use the Hex icon, which is the Elixir package manager (and where our documentation is also stored). Here it is: https://hex.pm/favicon.ico

Not sure on iconography, though -- both icons in place of the "Projects" nav item? Hmmm.

**Comment by bruce** [comment]
I've actually changed my mind -- a GitHub link to the right of the "Projects" nav item, linking to the GH org, is the right move.
